# Generated by Django 5.0.2 on 2024-02-22 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(auto_now_add=True, verbose_name='Start Game Date and time')),
                ('end_dt', models.DateTimeField(blank=True, null=True, verbose_name='End Game Date and time')),
                ('imposter_count', models.PositiveIntegerField(default=0, verbose_name='Count of traitors in game')),
                ('imposter_max', models.PositiveIntegerField(default=1, verbose_name='Max count of traitors in game')),
                ('players_count', models.PositiveIntegerField(default=0, verbose_name='Count of players in game')),
                ('players_max', models.PositiveIntegerField(default=2, verbose_name='Max count of players in game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP Address of player')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP Address of player')),
                ('is_imposter', models.BooleanField(default=False, verbose_name='Is imposter?')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
