# Generated by Django 5.0.3 on 2024-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='imposter_count',
            new_name='traitors_count',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='imposter_max',
            new_name='traitors_max',
        ),
        migrations.RenameField(
            model_name='gameplayer',
            old_name='is_imposter',
            new_name='is_traitor',
        )
    ]
